use_frameworks!

target 'CCIAbacusView_Example' do
  pod 'CCIAbacusView', :git => 'https://github.com/ccosnean/CCIAbacusView.git'

  target 'CCIAbacusView_Tests' do
    inherit! :search_paths

    
  end
end
